### PR TITLE
sqlite open as readonly db

### LINKED ISSUE #77: sqlite databases should be accessed in readonly mode
Currently the code (most artifact modules) just uses sqlite3.connect() which will alter the db, and remove the -wal file too.

### PR DESCRIPTION
**Pull request by ydkhatri**
Fixes #77 
All future modules should use `open_sqlite_db_readonly(path)` from ilapfuncs instead of `sqlite3.connect(path)`

I will be making the same edits to ileapp too tomorrow.

### CODE REVIEW

**Comment by abrignoni** [comment]
This is good stuff. I had no idea there was a function for it. 👏 👏 👏

**Comment by ydkhatri** [comment]
I finally got around to implementing this, it's been a long time. Can you test this and make sure it works ok, before merging?

**Comment by abrignoni** [comment]
Screen Shot 2020-11-20 at 9 42 00 PM
Artifact needs to be renamed. Going to test now.

**Comment by stark4n6** [comment]
I think it's case sensitive, was working on stuff yesterday and saw this. Rename to be lowercase.

**Comment by abrignoni** [comment]
Lowercased it. Going to compare master with the output of the PR. 
BRB....

**Comment by abrignoni** [comment]
Worked like a charm. Did some random checks. No changes in output so far. That being said this is a great improvement for the obvious forensic implications. Thanks @ydkhatri. Learned something new. Obligatory tweet incoming. LOL!
Merging pull request.

**Comment by ydkhatri** [comment]
I blame git. I think since I renamed the file on Windows, git did not take notice.

**Pull request merged**
