### PR TITLE
Minor change to GUI with option to select which modules to run

### PR DESCRIPTION
**Pull request by oleg4n6**
Hi. Please review and commit if you like it.

### CODE REVIEW

**Comment by ydkhatri** [comment]
I haven't seen the code but it isn't working for me. See screenshot below. I can't see any modules listed.
Capture

**Comment by oleg4n6** [comment]
Looks like you have not selected any dataset yet. Try to select archive or
folder first.

**Comment by abrignoni** [comment]
Did you do a recent file fetch before making the additions to the code? 
For example the csv option is not valid anymore since the code generates tab separated values file per artifact at artifact generation. That is why the checkbox is not on the GUI anymore currently. Not sure why it is back .

I wasn't able to get the modules listed either even after selecting a tar file. That being said the concept is fantastic and the screen layout looks great. I'm liking it a lot. 

For reference I am pointing it to one of Josh Hickman's images. Please advise. I would love to see this functionality in action. Good stuff.

**Comment by oleg4n6** [comment]
Hmmm.  Cloned your image yesterday.  I’ll try to redo it
today/tomorrow/Over the weekend.

**Comment by abrignoni** [comment]
Weird. I bet it didn't fetch correctly since the master now requires the
user to provide a directory location to place the reports on. It doesn't
default to the script directory anymore.

**Comment by oleg4n6** [comment]
Fixed now (?) I hope :). Please let me know if it doesn't work (still
learning github).

**Comment by ydkhatri** [comment]
Closing, since the subsequent pull was merged!

**Pull request closed without merging**
