### PR TITLE
Google music

### PR DESCRIPTION
**Pull request by abrignoni**
Parses Google Music history. SQLite DB has a protobuf field. Could be parsed more efficiently with the newer protobuf implementation. Currently writing blobs out from DB to disk to then parse. Makes me sad.

### CODE REVIEW

**Comment by abrignoni** [comment]
Sample test data:
[GoogleMusicTestData.zip](https://github.com/abrignoni/ALEAPP/files/4364790/GoogleMusicTestData.zip)

**Comment by ydkhatri** [comment]
ok, will take a look shortly.

**Comment by abrignoni** [comment]
Going to change the search expression and the names of the artifact. The database does not have the .sqlite extension in the original extraction. This is what happens when I work with provided test data. LOL. Just fyi. Not touching anything else.

**Comment by ydkhatri** [comment]
Got it. Also what version of android or google music is this? I am not seeing this in any of the images I have.

**Comment by abrignoni** [comment]
Changed the name. Is called Playing Now. Got it from Kevin Pagano. Let me
ask him about versions and whatnot.

**Comment by abrignoni** [comment]
Android 10, app is Now Playing, built into the Pixel series starting at v2.
It's part of the Ambient Services found here,
https://play.google.com/store/apps/details?id=com.google.intelligence.sense

**Comment by ydkhatri** [comment]
OK, so its not Google Music at all, but another service that's showing you _any music playing nearby_, according to their description.

**Comment by abrignoni** [comment]
Yes. That is why I changed the name from Music to Playing Now as stated previously. 

Interesting the fact about keeping track of any music playing nearby. Did not know about that.

**Pull request merged**
