### PR TITLE
Dark mode + sorted plugins in GUI

### PR DESCRIPTION
**Pull request by ydkhatri**
With increasing number of plugins, it is better to have a sorted list for easy selection.

image

### CODE REVIEW

**Comment by abrignoni** [comment]
This looks infinitely better than how it was. I like it.

**Comment by ydkhatri** [comment]
Version number updated to 1.3 now.

**Comment by abrignoni** [comment]
Going to build binaries for release now.

**Comment by ydkhatri** [comment]
I just realized that I need to remove the .py from names, as sometimes it is not the same.

**Comment by ydkhatri** [comment]
Please wait for one more change

**Comment by abrignoni** [comment]
Will do

**Comment by abrignoni** [comment]
Dark mode is so good!!!!
I Want to make it the default. LOL!
Will do release when advised.

This is pretty cool.

**Comment by ydkhatri** [comment]
Done now. Also making corresponding changes to ileapp, should be ready in few min too.

**Comment by abrignoni** [comment]
Perfect. Will do binaries for iLEAPP also when you are done.

**Comment by abrignoni** [comment]
Made the ALEAPP binaries. Getting this error at the end. Everything works
fine if run as a python script and not a exe.

**Comment by abrignoni** [comment]
Made the ALEAPP binaries. Getting this error at the end. Everything works fine if run as a python script and not a exe.

Capture

**Comment by abrignoni** [comment]
It is a spec file issue. Fixing now.

**Comment by abrignoni** [comment]
Fixed.

**Pull request merged**
