### PR TITLE
Small feature updates

### PR DESCRIPTION
**Pull request by ydkhatri**
Add parsing for Usagestats v2 (Android 11)
Make nav bar retain its position when you click on an item, it was quite annoying if you clicked on an artifact report after scrolling down and then the scrollbar (for left pane) was right back at the top, and you had to scroll again!
Adds extra space after the last item in nav bar (wifi) , so it isn't covered up by link preview of browser.
Some other minor fixes

Please test the usagestats, I hope it didn't break anything. Works fine on my end, but did not test with mac/linux or other py versions.

### CODE REVIEW

**Comment by abrignoni** [comment]
Omg! The scroll bar fix for ileapp too!!! 🙏

**Comment by ydkhatri** [comment]
Yes, I can do that in 2 min. now.

**Comment by abrignoni** [comment]
Thank you! Whoohooo!

**Comment by ydkhatri** [comment]
OK, wait, just found a bug. Will fix this first. This somehow skips index.html, as its written out in a different function. Will fix it now.

**Comment by ydkhatri** [comment]
All fixed now, please test. Checking in ileapp now.

**Comment by abrignoni** [comment]
Android 10 all good.
Android 11:
Screen Shot 2020-11-16 at 11 12 01 PM

Screen Shot 2020-11-16 at 11 12 11 PM

Checked the usagestgats folder and there is data there. Not sure why it wouldn't copy the stuff over. All other artifacts worked fine.

Using Josh Hickman's Android 11 tar.

**Comment by abrignoni** [comment]
Actually the data is in the temp folder. Just looked.

**Comment by ydkhatri** [comment]
I had to adjust the grep search term, all good now.

**Comment by ydkhatri** [comment]
OK, now tested with all format (tar, zip, fs) with all modules. Apparently, another module also extracts the parent folder, hence the overwrite errors. All fixed now.

**Pull request merged**
